app = 'fly-log-shipper-mgf'
primary_region = 'lhr'

[build]

[env]
  ORG = 'microgridfoundry'
  PAPERTRAIL_ENDPOINT = 'https://logs3.papertrailapp.com:23124'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
