app = 'fly-log-shipper-bec'
primary_region = 'lhr'

[build]
  ignorefile = ".dockerignore.bec"

[env]
  ORG = 'bristolenergy'
  QUEUE = 'bec'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
